//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurivisa_v2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public int ID { get; set; }
        public string LINK { get; set; }
        public string SEO_TITLE { get; set; }
        public string SEO_DESCRIPTION { get; set; }
        public string IMG_DESCRIPTION { get; set; }
        public string TEXT_DESCRIPTION { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public string AUTHOR { get; set; }
        public Nullable<int> VIEW_NUMBER { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<bool> POST_STATE { get; set; }
        public string TITLE { get; set; }
        public string IMG { get; set; }
    
        public virtual CATEGORY CATEGORY1 { get; set; }
    }
}
